name: "Output Information"
on: workflow_dispatch


env:
  myNull: ${{ null }}
  myBoolean: ${{ false }}
  myIntegerNumber: ${{ 711 }}
  myFloatNumber: ${{ -9.2 }}
  myHexNumber: ${{ 0xff }}
  myExponentialNumber: ${{ -2.99e-2 }}
  myString: Mona the Octocat
  myStringInBraces: ${{ 'It''s open source!' }}

jobs:
   info:
      runs-on: ubuntu-latest
      steps:
         - name: "Output Github context"
           run: echo "${{ toJSON(github) }}"
